apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true

# spot: ture is only used for Development environment. 
# if you are not given spot:true --> then it will become as a On-demand-Instance, so Cost anedi yekkuava padutumdhi. Moreover On-demand antee ika yavvaru tisukoru mana Instances ni. 
# Eppudu spot: true ani echhinappudu, oka 2 mins Notice period echhi tisukuntaee instance max 1 0r 2 Instnace ni matrame.
# then ventaney delete ina instance vere worker nodes loki veltai andi few sec lo ney malli new node kuda create avutmdhi.  