apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true

# if you are not given spot:true --> then it will become as a On-demand-Instance, so Cost anedi yekkuava padutumdhi.
# spot: ture is only used for Development environment. 